name:                baby-l4
version:             0.1.2.1
github:              "smucclaw/baby-l4"
license:             BSD3
author:              "Wong Meng Weng"
maintainer:          "mwwong@smu.edu.sg"
copyright:           "2022"

extra-source-files:
- README.org
- grammars/Prop.gf
- grammars/Answer.gf
- grammars/Questions.gf
- grammars/Predicates.gf
- grammars/ParsePredicates.gf

data-files:
- l4/Prelude.l4
- grammars/Prop.gf
- grammars/PropI.gf
- grammars/PropEng.gf
- grammars/Atoms.gf
- grammars/AtomsEng.gf
- grammars/Answer.gf
- grammars/AnswerEng.gf
- grammars/Questions.gf
- grammars/QuestionsEng.gf
- grammars/Predicates.gf
- grammars/PredicatesEng.gf
- grammars/ReducedWordNet.gf
- grammars/ReducedWordNetEng.gf
- grammars/ParsePredicates.labels
- grammars/ParsePredicatesEng.labels
- grammars/ExtendEng.gfo

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         baby-l4 provides the core language to which natural4 compiles.

dependencies:
- base >= 4.7 && < 5
- array
- containers
- pretty-simple
- prettyprinter >= 1.7.0
- split
- text
- extra
  # required for lexer and parser
- haskeline
- mtl
  # required for GF
- gf
- gf-ud
  # required for SCasp abs.syn.
- megaparsec
  # Required for lexer/lsp interop
- lsp-types
- MissingH
  # required for SMT interaction
- simple-smt
- sbv
  # required for graph processing (rule transformation)
- fgl
- graphviz
  # for package Util
- ghc
- tasty
- tasty-hunit
  # required for lsp
- lsp
- lsp-types
- haskeline
- mtl
- lens
- hslogger
- sorted-list
- either
- transformers
- rope-utf16-splay
- mmorph
- optparse-applicative

ghc-options: -Wall -Wno-missed-extra-shared-lib

library:
  source-dirs: src
  dependencies:
  - l4-generated

custom-setup:
  dependencies:
    - filepath
    - base >= 4.7 && < 5
    - Cabal == 3.6.3.0

internal-libraries:
  l4-generated:
    exposed-modules:
      # generated from GF grammars
      - Prop
      - Answer
      - Questions
      - ParsePredicates
      - Predicates

    dependencies:
    - gf
    build-tools: gf:gf
    ghc-options: []
    source-dirs:
      - grammars
    language: Haskell2010

executables:
  l4:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -H500M -qg"'
    dependencies:
    - baby-l4
    - l4-generated

#  lsp-server-bl4:
#    main:                Main.hs
#    source-dirs:         lsp
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - '"-with-rtsopts=-N -H500M -qg"'
#    dependencies:
#    - baby-l4
#    - l4-generated


#tests:
  # lsp-server-tests:
  #   main:                Spec.hs
  #   source-dirs:         lsp-tests
  #   ghc-options:
  #   - Wall
  #   dependencies:
  #   - tasty
  #   - tasty-hunit
  #   - tasty-expected-failure
  #   - baby-l4
  #   - l4-generated
  #   - lsp-test
  #   - lsp-types
  #   - text

