resolver: lts-21.20

packages:
  - .

extra-deps:
- github: smucclaw/gf-core
  commit: e11017abc0c91ff5b4c4da48e25b355b5704c2a8
- github: mengwong/compact
  commit: 214867cfd0868c02313e97f29215d48545458da3
- github: yav/simple-smt  
  commit: dd03ca1

allow-newer: true

# Required for the option custom-preprocessor-extensions
require-stack-version: ">= 2.7.1"
# This will show a warning
custom-preprocessor-extensions:
- gf

flags:
  # this excludes PGF2 module in gf package
  gf:
    c-runtime: false
    server: false
  regex-posix:
    _regex-posix-clib: true

# nix:
#   enable: true
#   pure: false
