resolver: lts-21.14

packages:
  - .

extra-deps:
- github: smucclaw/gf-core
  commit: 2acf677848e0d9fe930c1aa74e32c2c9f6a44a99
- github: mengwong/compact
  commit: 214867cfd0868c02313e97f29215d48545458da3
- github: yav/simple-smt  
  commit: dd03ca1

# Required for the option custom-preprocessor-extensions
require-stack-version: ">= 2.7.1"
# This will show a warning
custom-preprocessor-extensions:
- gf

flags:
  # this excludes PGF2 module in gf package
  gf:
    c-runtime: false
    server: false
  regex-posix:
    _regex-posix-clib: true

# nix:
#   enable: true
#   pure: false
