resolver: lts-20.26

packages:
  - .

extra-deps:
# - github: smucclaw/gf-core
#   commit: edb55df7b0c4892ba0bac2817b5f493921c20c36
- github: mengwong/compact
  commit: 214867cfd0868c02313e97f29215d48545458da3
- github: yav/simple-smt  
  commit: dd03ca1

# Required for the option custom-preprocessor-extensions
require-stack-version: ">= 2.7.1"
# This will show a warning
# custom-preprocessor-extensions:
# - gf

flags:
  # this excludes PGF2 module in gf package
  # gf:
  #   c-runtime: false
  #   server: false
  regex-posix:
    _regex-posix-clib: true

# nix:
#   enable: true
#   pure: false
