resolver: lts-22.10

packages:
  - .

extra-deps:
- github: smucclaw/gf-core
  commit: f9dedf46e04c5e6cd0ab2a3af6d36c15f3d062ac
# - github: mengwong/compact
#   commit: 214867cfd0868c02313e97f29215d48545458da3

- simple-smt-0.9.7

allow-newer: true

# Required for the option custom-preprocessor-extensions
require-stack-version: ">= 2.7.1"
# This will show a warning
custom-preprocessor-extensions:
- gf

flags:
  # this excludes PGF2 module in gf package
  gf:
    c-runtime: false
    server: false
  regex-posix:
    _regex-posix-clib: true

# nix:
#   enable: true
#   pure: false
