name: Build and run tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  flakes-simple:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - name: Cache Haskell stack
        uses: actions/cache@v4
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('lib/haskell/**/package.yaml','lib/haskell/**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('lib/haskell/**/package.yaml','lib/haskell/**/stack.yaml.lock') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('lib/haskell/**/package.yaml') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # - name: Install libcurl on Ubuntu
      #   if: startsWith(matrix.os, 'ubuntu')
      #   run: sudo apt-get install libcurl4-openssl-dev
      # - name: Install libcurl on macos
      #   if: startsWith(matrix.os, 'macOS')
      #   run: brew install openssl && brew install curl && export PATH="/opt/homebrew/opt/curl/bin:$PATH"'

      - name: Build and test baby-l4
        run: stack test